# HTTP Server
[server]
  address     = ":8080"
  name = "xx"
  readTimeout = "1s"
  writeTimeout = "1s"

# Logger.
[logger]
  maxSize = 1
  path        = "runtime"

# Database.
[db]
  host = "127.0.0.1"
  port = "3306"
  user = "root"
  password = "123456"
  database = "vh_dingtalk"
  prefix = "vh_"
  connTimeOut = "5s"
  readTimeout = "1s"
  writeTimeout = "2s"
  #链接池
  maxIdleConns = 10
  maxOpenConns = 200
  connMaxLifetime = "10s"

# Redis数据库配置
[redis]
  host = "127.0.0.1"
  port = 6379
  db = 0
  password = ""
  readTimeout = "1s"
  writeTimeout = "2s"
  connectTimeout = "10s"
  maxIdle = 50
  maxActive = 10000
  idleTimeout = "60s"

#http请求配置
[httpclient]
  timeout = 2